from tkinter import *
root=Tk()
root.geometry("400x450")
root.title("Simple Calculator")
root.configure(bg="purple")

def click(event):
    global scvalue
    text=event.widget.cget('text')
    if text=='=':
        if scvalue.get().isdigit():
            value=int(scvalue.get())
        else:
            value=eval(scvalue.get())
        scvalue.set(value)
        screen.update()
    elif text=='C':
        scvalue.set('')
        screen.update()
    else:
        scvalue.set(scvalue.get()+text)
        screen.update()

scvalue=StringVar()
scvalue.set('')
screen=Entry(root,textvar=scvalue,font='times 20 bold')
screen.pack(fill=X,padx=10,pady=16)
f=Frame(root,bg="red")
b=Button(f,text="C",font="lucida 30 bold",padx=20,bg="orange",border=3)
b.pack(side=LEFT,padx=2,pady=2)
b.bind('<Button-1>',click)
b=Button(f,text="/",font="lucida 30 bold",padx=28,bg="orange",border=3)
b.pack(side=LEFT,padx=2,pady=2)
b.bind('<Button-1>',click)
b=Button(f,text="*",font="lucida 30 bold",padx=24,bg="orange",border=3)
b.pack(side=LEFT,padx=2,pady=2)
b.bind('<Button-1>',click)
b=Button(f,text="-",font="lucida 30 bold",padx=24,bg="orange",border=3)
b.pack(side=LEFT,padx=2,pady=2)
b.bind('<Button-1>',click)
f.pack()
f=Frame(root,bg="red")
b=Button(f,text="7",font="lucida 30 bold",padx=21,bg="orange",border=3)
b.pack(side=LEFT,padx=2,pady=2)
b.bind('<Button-1>',click)
b=Button(f,text="8",font="lucida 30 bold",padx=20,bg="orange",border=3)
b.pack(side=LEFT,padx=2,pady=2)
b.bind('<Button-1>',click)
b=Button(f,text="9",font="lucida 30 bold",padx=21,bg="orange",border=3)
b.pack(side=LEFT,padx=2,pady=2)
b.bind('<Button-1>',click)
b=Button(f,text="+",font="lucida 30 bold",padx=16,bg="orange",border=3)
b.pack(side=LEFT,padx=2,pady=2)
b.bind('<Button-1>',click)
f.pack()
f=Frame(root,bg="red")
b=Button(f,text="4",font="lucida 30 bold",padx=20,bg="orange",border=3)
b.pack(side=LEFT,padx=2,pady=2)
b.bind('<Button-1>',click)
b=Button(f,text="5",font="lucida 30 bold",padx=20,bg="orange",border=3)
b.pack(side=LEFT,padx=2,pady=2)
b.bind('<Button-1>',click)
b=Button(f,text="6",font="lucida 30 bold",padx=22,bg="orange",border=3)
b.pack(side=LEFT,padx=2,pady=2)
b.bind('<Button-1>',click)
b=Button(f,text=".",font="lucida 30 bold",padx=25,bg="orange",border=3)
b.pack(side=LEFT,padx=2,pady=2)
b.bind('<Button-1>',click)
f.pack()
f=Frame(root,bg="red")
b=Button(f,text="1",font="lucida 30 bold",padx=20,bg="orange",border=3)
b.pack(side=LEFT,padx=2,pady=2)
b.bind('<Button-1>',click)
b=Button(f,text="2",font="lucida 30 bold",padx=20,bg="orange",border=3)
b.pack(side=LEFT,padx=2,pady=2)
b.bind('<Button-1>',click)
b=Button(f,text="3",font="lucida 30 bold",padx=20,bg="orange",border=3)
b.pack(side=LEFT,padx=2,pady=2)
b.bind('<Button-1>',click)
b=Button(f,text="0",font="lucida 30 bold",padx=20,bg="orange",border=3)
b.pack(side=LEFT,padx=2,pady=2)
b.bind('<Button-1>',click)
f.pack()
f=Frame(root,bg="red")
b=Button(f,text="=",font="lucida 30 bold",padx=140,bg="orange",border=3)
b.pack(side=LEFT,padx=2,pady=2)
b.bind('<Button-1>',click)
f.pack()

root.mainloop()